### PR TITLE
Support snippets in `tsx` files

### PR DESCRIPTION
**Pull request by arafatamim**

### CODE REVIEW

**Comment by tmueller** [comment]
Hi @juanojeda,

would you be so kind to merge? Thanks for creating the plugin :)

**Review by juanojeda — APPROVED** [review]

**Comment by tmueller** [comment]
Hi @juanojeda, 

now that it is merged, could you be so kind to release it to vscode marketplace? Thanks a lot.

**Comment by juanojeda** [comment]
@tmueller @arafatamim Published, apologies for the delay on that!

**Comment by tmueller** [comment]
No apology necessary 🙂 . Thanks for spending your time to improve vscode for others.

**Pull request merged**
